// Généré par scripts/soldier-sprites.mjs — ne pas modifier à la main.
export const SOLDIER_IMAGES: Record<string, number> = {
  'soldier-wild-0': require('../../../assets/soldiers/soldier-wild-0.png'),
  'captain-wild-0': require('../../../assets/soldiers/captain-wild-0.png'),
  'soldier-1-1': require('../../../assets/soldiers/soldier-1-1.png'),
  'captain-1-1': require('../../../assets/soldiers/captain-1-1.png'),
  'soldier-1-2': require('../../../assets/soldiers/soldier-1-2.png'),
  'captain-1-2': require('../../../assets/soldiers/captain-1-2.png'),
  'soldier-1-3': require('../../../assets/soldiers/soldier-1-3.png'),
  'captain-1-3': require('../../../assets/soldiers/captain-1-3.png'),
  'soldier-1-4': require('../../../assets/soldiers/soldier-1-4.png'),
  'captain-1-4': require('../../../assets/soldiers/captain-1-4.png'),
  'soldier-1-5': require('../../../assets/soldiers/soldier-1-5.png'),
  'captain-1-5': require('../../../assets/soldiers/captain-1-5.png'),
  'soldier-1-6': require('../../../assets/soldiers/soldier-1-6.png'),
  'captain-1-6': require('../../../assets/soldiers/captain-1-6.png'),
  'soldier-2-1': require('../../../assets/soldiers/soldier-2-1.png'),
  'captain-2-1': require('../../../assets/soldiers/captain-2-1.png'),
  'soldier-2-2': require('../../../assets/soldiers/soldier-2-2.png'),
  'captain-2-2': require('../../../assets/soldiers/captain-2-2.png'),
  'soldier-2-3': require('../../../assets/soldiers/soldier-2-3.png'),
  'captain-2-3': require('../../../assets/soldiers/captain-2-3.png'),
  'soldier-2-4': require('../../../assets/soldiers/soldier-2-4.png'),
  'captain-2-4': require('../../../assets/soldiers/captain-2-4.png'),
  'soldier-2-5': require('../../../assets/soldiers/soldier-2-5.png'),
  'captain-2-5': require('../../../assets/soldiers/captain-2-5.png'),
  'soldier-2-6': require('../../../assets/soldiers/soldier-2-6.png'),
  'captain-2-6': require('../../../assets/soldiers/captain-2-6.png'),
};
